Repository AppIntro/AppIntro, pull requests merged in 2020-01, with the labels that each got.

#731 Decrease Detekt Max Issues to 1
  appintro/detekt-config.yml
Labels: infra

#733 Move SampleSlide to library
  README.md
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroCustomLayoutSlide.kt
  example/src/main/java/com/amqtech/opensource/appintroexample/ui/mainTabs/intro/CustomLayoutIntro.java
  example/src/main/java/com/amqtech/opensource/appintroexample/util/SampleSlide.java
Labels: enhancement

#735 Added a parallax animation setting
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/internal/viewpager/ViewPagerTransformer.kt
  example/src/main/java/com/amqtech/opensource/appintroexample/ui/mainTabs/intro/DefaultIntro2.java
Labels: enhancement

#730 New Approach to Permission & Cleanup
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroViewPager.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/internal/PermissionWrapper.kt
  example/src/main/java/com/amqtech/opensource/appintroexample/ui/permsTabs/intro/PermissionsIntro2.java
Labels: enhancement

#738 Fix button state not being retained on configuration change
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.kt
Labels: bug

#739 Fix Visibility leakage before releasing 6.0.0
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntro.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntro2.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroBaseFragment.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroViewPagerListener.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/internal/AppIntroViewPager.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/internal/viewpager/ViewPagerTransformer.kt
  appintro/src/main/java/com/github/paolorotolo/appintro/model/SliderPage.kt
  appintro/src/main/res/layout/appintro_intro_layout.xml
  appintro/src/main/res/layout/appintro_intro_layout2.xml
Labels: bug

#742 Fix Crash on orientation changes due to UninitiatedPropertyAccessException
  appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.kt
Labels: bug
