Repository AppIntro/AppIntro, pull requests merged in 2020-06, with the labels that each got.

#802 Fix goToNextSlide default param for RTL
  appintro/src/main/java/com/github/appintro/AppIntroBase.kt
  appintro/src/main/java/com/github/appintro/internal/AppIntroViewPager.kt
Labels: bug

#808 Fix isButtonsEnabled being reset to true after onCreate
  appintro/src/main/java/com/github/appintro/AppIntroBase.kt
Labels: bug

#809 Gradle to 6.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: infra

#815 AGP to 4.0.0
  build.gradle
Labels: infra

#814 KtLint to 0.37.0
  appintro/build.gradle
Labels: infra

#813 Detekt to 1.9.1
  build.gradle
  config/detekt/detekt.yml
Labels: infra

#817 enabling backward sliding when slide policy not met
  appintro/src/main/java/com/github/appintro/internal/AppIntroViewPager.kt
Labels: bug

#816 Cleanup the Sample App
  appintro/src/test/java/com/github/appintro/model/SliderPageBuilderTest.kt
  assets/sample-app.png
  example/build.gradle
  example/example-release-v1.apk
  example/example-release-v2.apk
  example/src/main/AndroidManifest.xml
  example/src/main/java/com/github/appintro/example/ui/IntroAdapter.kt
  example/src/main/java/com/github/appintro/example/ui/IntroEntry.kt
  example/src/main/java/com/github/appintro/example/ui/MainActivity.kt
  example/src/main/java/com/github/appintro/example/ui/custom/CustomBackgroundIntro.kt
  example/src/main/java/com/github/appintro/example/ui/custom/CustomLayoutIntro.kt
  example/src/main/java/com/github/appintro/example/ui/default/DefaultIntro.kt
  example/src/main/java/com/github/appintro/example/ui/default/DefaultIntro2.kt
  example/src/main/java/com/github/appintro/example/ui/fragment/MainTabsFragment.kt
  example/src/main/java/com/github/appintro/example/ui/fragment/PermissionTabsFragment.kt
  example/src/main/java/com/github/appintro/example/ui/mainTabs/CustomBackgroundIntro.kt
  example/src/main/java/com/github/appintro/example/ui/mainTabs/CustomLayoutIntro.kt
  example/src/main/java/com/github/appintro/example/ui/mainTabs/DefaultLayout2Intro.kt
  example/src/main/java/com/github/appintro/example/ui/mainTabs/DefaultLayoutIntro.kt
  example/src/main/java/com/github/appintro/example/ui/mainTabs/MainPagerAdapter.kt
  example/src/main/java/com/github/appintro/example/ui/permissions/PermissionsIntro.kt
  example/src/main/java/com/github/appintro/example/ui/permissions/PermissionsIntro2.kt
  example/src/main/java/com/github/appintro/example/ui/permsTabs/PermissionsLayout1Intro.kt
  example/src/main/java/com/github/appintro/example/ui/permsTabs/PermissionsLayout2Intro.kt
  example/src/main/java/com/github/appintro/example/ui/permsTabs/PermsPagerAdapter.kt
  example/src/main/java/com/github/appintro/example/util/FragmentStatePagerAdapter.java
  example/src/main/java/com/github/appintro/example/util/TabLayout.java
  example/src/main/java/com/github/appintro/example/util/TabStrip.java
  example/src/main/res/color/selector.xml
  example/src/main/res/drawable/ic_sample_bg.png
  example/src/main/res/layout-v21/activity_main.xml
  example/src/main/res/layout-v21/fragment_main_tabs.xml
  example/src/main/res/layout-v21/fragment_permission_tabs.xml
  example/src/main/res/layout/activity_main.xml
  example/src/main/res/layout/fragment_main_tabs.xml
  example/src/main/res/layout/fragment_permission_tabs.xml
  example/src/main/res/layout/item_intro.xml
  example/src/main/res/layout/tab_custom_background_intro.xml
  example/src/main/res/layout/tab_custom_layout_intro.xml
  example/src/main/res/layout/tab_default_intro.xml
  example/src/main/res/layout/tab_default_intro2.xml
  example/src/main/res/layout/tab_permissions_1.xml
  example/src/main/res/layout/tab_permissions_2.xml
  example/src/main/res/layout/util_drawer_hdr.xml
  example/src/main/res/values-de/strings.xml
  example/src/main/res/values-es/strings.xml
  example/src/main/res/values-v19/styles.xml
  example/src/main/res/values-w820dp/dimens.xml
  example/src/main/res/values/colors.xml
  example/src/main/res/values/dimens.xml
  example/src/main/res/values/strings.xml
  example/src/main/res/values/styles.xml
Labels: enhancement

#821 Fix bug with SetSwipeLock being reset to false
  appintro/src/main/java/com/github/appintro/AppIntroBase.kt
Labels: bug

#825 Added ability to color back arrow and done button
  appintro/src/main/java/com/github/appintro/AppIntro.kt
Labels: enhancement

#829 Update Persian localization
  appintro/src/main/res/values-fa/strings.xml
Labels: translation

#827 Put slide transformers side by side in README
  README.md
Labels: documentation

#831 Finish the French translation
  appintro/src/main/res/values-fr/strings.xml
Labels: translation
