Repository AppIntro/AppIntro, pull requests merged in 2020-10, with the labels that each got.

#877 Tamil translation added
  appintro/src/main/res/values-ta/strings.xml
Labels: translation

#871 Added Java Example for App Intro
  example/src/main/AndroidManifest.xml
  example/src/main/java/com/github/appintro/example/ui/IntroEntry.kt
  example/src/main/java/com/github/appintro/example/ui/default/DefaultIntro2.kt
  example/src/main/java/com/github/appintro/example/ui/java/JavaIntro.java
  example/src/main/res/values/strings.xml
Labels: documentation

#879 Removed non working links + corrected spelling mistake
  README.md
Labels: documentation

#876 Single slide indicator condition issue504
  appintro/src/main/java/com/github/appintro/indicator/DotIndicatorController.kt
Labels: enhancement

#883 Changing Visibility of Progress Bar when count of silde is one
  appintro/src/main/java/com/github/appintro/indicator/ProgressIndicatorController.kt
Labels: enhancement

#886 Fixed Readme permissions example mistake
  README.md
Labels: documentation

#888 Bump several dependencies
  appintro/build.gradle
  appintro/src/main/java/com/github/appintro/indicator/DotIndicatorController.kt
  build.gradle
  example/build.gradle
Labels: infra

#892 Run Pre merge checks only on master
  .github/workflows/pre-merge.yml
Labels: infra

#891 Do not show back arrow on wizard mode on first slide
  appintro/src/main/java/com/github/appintro/AppIntroBase.kt
Labels: bug
