Repository AppIntro/AppIntro, pull requests merged in 2020-08, with the labels that each got.

#839 Complete the Chinese (Simplified) translation
  appintro/src/main/res/values-my
  appintro/src/main/res/values-zh-rCN/strings.xml
  appintro/src/main/res/values-zh-rTW/strings.xml
Labels: translation

#842 AGP to 4.0.1
  build.gradle
Labels: infra

#843 Bump Detekt and KtLint
  appintro/build.gradle
  build.gradle
Labels: infra

#856 Fix blending of Indicator Colors
  appintro/src/main/java/com/github/appintro/indicator/DotIndicatorController.kt
  appintro/src/main/java/com/github/appintro/indicator/IndicatorController.kt
  appintro/src/main/java/com/github/appintro/indicator/ProgressIndicatorController.kt
  appintro/src/main/res/drawable/ic_appintro_indicator.xml
  appintro/src/main/res/drawable/ic_appintro_indicator_unselected.xml
  appintro/src/main/res/layout/appintro_intro_layout.xml
  appintro/src/main/res/layout/appintro_intro_layout2.xml
Labels: enhancement
